### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mhubbard** [openwide-java/tomcat-classloader-ordered#1]
Hello,

Thank you for your ordered classloader, just wondering if you could attach a license to the project so I know to what extent I can use and modify this project. For example I would like to make a change to ignore case to give a more true alphabetical order and use it in our platform. 

Thanks in advance.

**Comment by nwinkler** [comment]
Same here - we won't be able to use this without a license. Can you please clarify the licensing terms of this code? Ideally with a non-GPL license (MIT?)...

**Comment by gsmet** [comment]
Hi!

Sorry about that, I missed the first message. The code is licensed under the Apache License 2 (like Tomcat itself). I added the relative information in the README.md and a LICENSE file.

It was just a pet project, we didn't think about people reusing it at the time :).

## 

Guillaume

**Comment by nwinkler** [comment]
@gsmet Thanks - you rock! 🍻
